### ISSUE TITLE
Upgrade Contract

### ISSUE THREAD

**Issue by selimerunkut** [CypherX-LLC/bep20_NVM#1]
add functionality for fees; 
see: https://github.com/selimerunkut/bep20_NNN/blob/52f0541a7cf7625b157b23dac1fba0e3515a1916/src/EnhancedMinterPauser.sol#L85

**Comment by selimerunkut** [comment]
I don't see a version 1 and V2 for the upgrade of the contract, there should be a old version of the contract V1 and a new version `src/NVMToken.sol_V2` ?

**Comment by 0x471** [comment]
> I don't see a version 1 and V2 for the upgrade of the contract, there should be a old version of the contract V1 and a new version `src/NVMToken.sol_V2` ?

I did, could you please check it?

**Comment by selimerunkut** [comment]
Add/modify deploy script

add upgrade test 

add missing tests for the new functionality

**Comment by 0x471** [comment]
Testing the upgrade on BSC testnet. 

1) Proxy address shouldn't change
2) Name and Symbol should be same.

**Comment by 0x471** [comment]
Tested on BSC testnet. Proxy address, name and the symbol are the same.
